#!/usr/bin/env python
"""
Initially Generated By:
    python -m utool --tf setup_repo --repo=dtool_ibeis --codedir=~/code --modname=dtool_ibeis
"""


def dtool_main():
    ignore_prefix = []
    ignore_suffix = []
    import utool as ut
    # allows for --tf
    ut.main_function_tester('dtool_ibeis', ignore_prefix, ignore_suffix)

if __name__ == '__main__':
    """
    Usage:
        python -m dtool_ibeis --tf <funcname>
    """
    print('Running dtool_ibeis main')
    dtool_main()
